import { signIn } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>My Diary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="hero py-16">
        <div className="hero-content">
          <h1 className="text-4xl">
            <span className="text-5xl">Share your secrets</span>
            <br /> <span>Secured with your wallet key</span>
          </h1>
        </div>
      </section>

      <section className="flex flex-col items-center gap-4">
        <h1 className="text-3xl">Let me show you how</h1>
        <button onClick={() => void signIn()} className="btn btn-primary">Login with Ethereum</button>
      </section>
    </>
  );
}
